import os
import json
from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import JsonOutputParser
from models import QuizOutput  # Import our Pydantic model
from scraper import scrape_wikipedia # To test this file

# --- 1. Load Environment Variables ---
# (This loads the GOOGLE_API_KEY)
load_dotenv()

if not os.getenv("GOOGLE_API_KEY"):
    raise EnvironmentError("GOOGLE_API_KEY not found in .env file")

# --- 2. Initialize the LLM ---
# We'll use a specific model. 'gemini-1.5-flash' is fast and capable.
# 'temperature=0' makes the output deterministic and less "creative",
# which is good for factual quiz generation.
llm_model = ChatGoogleGenerativeAI(model="models/gemini-pro-latest", temperature=0)

# --- 3. Define the Output Parser ---
# This is the "magic" part. We create a parser that will
# use our 'QuizOutput' Pydantic model to:
#  a) Generate formatting instructions for the AI
#  b) Parse the AI's JSON output into a Python object
output_parser = JsonOutputParser(pydantic_object=QuizOutput)

# --- 4. Create the Prompt Template ---
# This is the detailed instruction manual for the AI.
# We pass it the 'scraped_text' and the 'format_instructions'
# (which are auto-generated by the output_parser).
prompt_template = """
You are an expert AI assistant that generates educational quizzes.
Your task is to create a quiz based *only* on the provided article text.

**Context:**
Here is the text from a Wikipedia article:
---
{scraped_text}
---

**Task:**
Based *only* on the text provided above, generate a complete quiz output.
You must adhere to the following JSON format:

{format_instructions}

**Rules:**
1.  **Strictly Factual:** All answers, summaries, and topics MUST come directly from the text. Do not add any external knowledge.
2.  **Title:** Use the 'title' from the text (I will provide it).
3.  **Summary:** Write a 2-3 sentence summary of the article.
4.  **Key Entities:** List the most important people, organizations, and locations mentioned.
5.  **Quiz:** Generate exactly 5 quiz questions.
6.  **Options:** Each question must have exactly 4 options (A, B, C, D).
7.  **Answer:** The 'answer' field must be one of the options.
8.  **Explanation:** The 'explanation' must be a brief quote or reference to where the answer is found in the text.
9.  **Related Topics:** List 3-5 related topics mentioned in the text.
"""

# Create the final prompt
prompt = ChatPromptTemplate.from_template(prompt_template)

# --- 5. Create the LLM Chain ---
# We use the LangChain Expression Language (LCEL) to "pipe"
# the components together.
#
# 1. 'prompt': Takes user input (text, title, sections)
# 2. 'llm_model': Sends the formatted prompt to Gemini
# 3. 'output_parser': Parses the LLM's JSON response into our Pydantic object
llm_chain = prompt | llm_model | output_parser

# --- Helper function to run the chain ---
def generate_quiz_from_text(scraped_data: dict):
    """
    Takes the dictionary from our scraper and runs the LLM chain.
    """
    try:
        print("--- Calling Gemini AI. This may take a moment... ---")
        
        # Get the format instructions from the parser
        format_instructions = output_parser.get_format_instructions()
        
        # Invoke the chain with all the required variables
        response = llm_chain.invoke({
            "scraped_text": scraped_data["clean_text"],
            "format_instructions": format_instructions,
            "title": scraped_data["title"], # Pass the title
            "sections": scraped_data["sections"] # Pass the sections
        })
        
        print("--- AI response received and parsed successfully! ---")
        return response
        
    except Exception as e:
        print(f"Error in LLM chain invocation: {e}")
        return None

# --- You can run this file directly to test it ---
if __name__ == "__main__":
    
    print("--- Starting LLM Generator Test ---")
    
    # 1. Scrape the article (using our working scraper.py)
    test_url = "https://en.wikipedia.org/wiki/Alan_Turing"
    print(f"Scraping {test_url}...")
    scraped_data = scrape_wikipedia(test_url)
    
    if scraped_data and scraped_data["clean_text"]:
        print("Scraping successful. Text extracted.")
        
        # 2. Generate the quiz
        quiz_data = generate_quiz_from_text(scraped_data)
        
        if quiz_data:
            # Print the output nicely using json.dumps
            print("\n--- Generated Quiz Data (JSON) ---")
            print(json.dumps(quiz_data, indent=2))
        else:
            print("Failed to generate quiz data.")
            
    else:
        print("Scraping failed. Cannot test LLM generator.")